### ISSUE TITLE
Script not running at startup

### ISSUE THREAD

**Issue by hiszd** [billyjbryant/obs-artifacts#1]
I am having an issue with the toggle_scene_source script.
I love your script, but for some reason when I close and re-launch OBS it stops working.
To get it to work again I need to either remove it and add it back, or click the "Defaults" button on the scripts window and input all of the values again. 
Reloading the script does not fix the issue.

I didn't find anything in the script logs to help debug this issue.

Update:
After logging some stuff in the script to the console and going through the different parts to find why it wasn't initializing at startup I discovered that in the initialization of the script it does not load the user preferences and attach a timer.
When the script starts it looks like it just assigns DEFAULT_SETTINGS to MY_SETTINGS and requires a property to be modified before it tries to write the user input to the MY_SETTINGS variable.
Is there a way to grab the user settings at startup?

**Comment by billyjbryant** [comment]
I will take a look and see what I can do to correct the issue you are seeing.

**Comment by hiszd** [comment]
This issue should be fixed with pull request #2

**Comment by billyjbryant** [comment]
Thank you for the PR, I merged it and will resolve this Issue.
